# Don't be alarmed when Selenium opens Chrome, this is needed for fetching data, as the data is
# loaded dynamically based on the fragments, and cannot be parsed via a standard. By isn't needed
# but the old way with just normal Selenium is deprecated anyways, so better to use it.
# Final parse is done using Beautiful Soup, since it's a little faster, but if you're a future subcomm
# reading this, feel free to use Selenium again if you only want to learn one.

from selenium import webdriver
from selenium.webdriver.common.by import By
from bs4 import BeautifulSoup
# This is only needed to get the strings for searching from conditions_processed.json, can implement a
# better way later
import json
import time

# Function to get all course codes from conditions_processed.json, since we need them as input
# into beautiful soup. Not good design, but it's temp helper and should be replaced with another
# source
course_data = {}
with open("../data/final_data/conditionsProcessed.json", "r") as file:
    data = json.load(file)
    keys = data.keys()

# Uses your version of Chrome to run the script, please have Chrome installed, or alternatively, rewrite this to
#use whatever you usually use
driver = webdriver.Chrome()
driver.get("https://www.unsw.edu.au/course-outlines/course-outline")

# Needs to accept cookies when working via Selenium unfortunately otherwise overlay will block access
# to form. Can also have information sent via Javascript execution probably, but no clue about UNSW's
# level of protection against external scripting.
#cookies_button = "onetrust-accept-btn-handler"
#cookies_button_submit = driver.find_element(By.ID, cookies_button)
#cookies_button_submit.click()
try:
    cookie_button = driver.find_element(By.ID, "onetrust-accept-btn-handler")
    cookie_button.click()
except:
    print("Cookie banner not found or already dismissed")

# This is the search form's Id
search_form_id = "degree-search-input"
search_form_submit_button = "degree-search-submit"
search_form = driver.find_element(By.ID, search_form_id)
search_form_submit = driver.find_element(By.ID, search_form_submit_button)
search_form.send_keys("COMP6080")
search_form_submit.click()
time.sleep(5)

# Finds first element that matches the pattern that is standard to the website
course_outline_page = driver.find_element(By.XPATH, "//a[span[normalize-space(text())='COMP6080']]")

# Note: We can cache the pages generated by this program to avoid parsing again, and just use the
# direct link using the below, however I recommend just reloading every time:
# course_outline_page.get_attribute("href")

html = driver.page_source
driver.quit()

# Puts the HTML in nicer beautiful soup format for the final parse, is quicker than using selenium
soup = BeautifulSoup(html, 'html.parser')

# Gets whether it's group work or not, all group work specifications is stored under a tag called description details,
# and it conveniently enough can be parsed out. There's a bunch of unrelated description details tags, so
# we get all the ones that contain the exact text "Group", since that's a standard way of formatting
# group projects or tasks worth a percentage of the mark for the course. The below is approximately the
# format from the webpage:
# <dt>Assessment Format: <dt> <dd>Group<dd>
potential_group_tags = soup.find_all('dd')
groupwork = False
for potential_group_tag in potential_group_tags:
    if potential_group_tag.get_text() == "Group":
        groupwork = True
        break
if groupwork:
    print("Success: Groupwork found in COMP6080!")
else:
    # If you are getting this error, either change the link at driver.get() to a course you
    # are certain has groupwork (At present it is COMP6080), and if it works you're good to go.
    # If it still doesn't work, it's time to see how the website's changed, my notes are above,
    # good luck
    print("I swear groupwork was part of this course, either it's been reworked, or the website's changed formats")