# Prerequisite: have Chrome installed or change the line driver = webdriver.Chrome() to whatever you prefer
# e.g. driver = webdriver.Firefox(). May want to multiprocess this later if impatient, use multiprocessing to
# get around Python's GIL (global interpreter lock), as threads are just secretly one.

# Don't be alarmed when Selenium opens Chrome, this is needed for fetching data, as the data is
# loaded dynamically based on the fragments, and cannot be parsed via a standard. By isn't needed
# but the old way with just normal Selenium is deprecated anyways, so better to use it. WebDriverWait
# and EC (expected conditions) are needed, as content is dynamically loaded, and otherwise failures
# may occur. If parsing using Selenium, remember to use expected conditions to wait for content to load before
# interacting with it
# Final parse is done using Beautiful Soup, since it's a little faster, but if you're a future subcomm
# reading this, feel free to use Selenium again if you only want to learn one.

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException
from bs4 import BeautifulSoup
# This is only needed to get the strings for searching from conditions_processed.json, can implement a
# better way later
import json
import time

# Wait a max of 20 second before giving up on a necessary element of a page loading. Most of the time, it won't take
# that long
MAX_WAIT_TIME = 20

# Function to get all course codes from conditions_processed.json, since we need them as input
# into beautiful soup. Not good design, but it's temp helper and should be replaced with another
# source
course_data = {}
with open("../data/final_data/conditionsProcessed.json", "r") as file:
    data = json.load(file)
    courses = data.keys()

# Uses your version of Chrome to run the script, please have Chrome installed, or alternatively, rewrite this to
#use whatever you usually use
driver = webdriver.Chrome()
driver.get("https://www.unsw.edu.au/course-outlines")

# Needs to accept cookies when working via Selenium unfortunately otherwise overlay will block access
# to form. Can also have information sent via Javascript execution probably, but no clue about UNSW's
# level of protection against external scripting.
#cookies_button = "onetrust-accept-btn-handler"
#cookies_button_submit = driver.find_element(By.ID, cookies_button)
#cookies_button_submit.click()
try:
    cookie_button = driver.find_element(By.ID, "onetrust-accept-btn-handler")
    cookie_button.click()
except:
    print("Cookie banner not found, possibly already handled")
    
for course in courses:
    # This is the search form's Id and the submit button's id, wait til they both exist and are clickable
    search_form_id = "degree-search-input"
    search_form_submit_button = "degree-search-submit"
    try:
        wait = WebDriverWait(driver, MAX_WAIT_TIME) 
        wait.until(
            EC.presence_of_element_located((By.ID, search_form_id))
        )
        wait.until(
            EC.element_to_be_clickable((By.ID, search_form_submit_button))
        )
    except TimeoutException:
        # Content not loaded in time
        print(f"Element not found on webpage. {course}")
        exit(1)
    search_form = driver.find_element(By.ID, search_form_id)
    search_form_submit = driver.find_element(By.ID, search_form_submit_button)
    search_form.send_keys(course)
    search_form_submit.click()

    # As content is dynamically loaded, wait until it is loaded to try getting the link
    try:
        wait = WebDriverWait(driver, MAX_WAIT_TIME) 
        wait.until(
            EC.element_to_be_clickable((By.XPATH,  f"//span[normalize-space(text())='{course}']"))
        )
    except TimeoutException:
        # Content not loaded in time
        print(f"Element not found on webpage. {course}")
        exit(1)

    # Finds first element that matches the pattern that is standard to the website
    course_outline_a = driver.find_element(By.XPATH, f"//a[span[normalize-space(text())='{course}']]")

    # Note: We can cache the pages generated by this program to avoid parsing again, and just use the
    # direct link using the below, however I recommend just reloading every time, since links will change
    # year to year. If you want to though, you can use this href
    course_outline_link = str(course_outline_a.get_attribute("href"))
    driver.get(course_outline_link)

    html = driver.page_source

    # Puts the HTML in nicer beautiful soup format for the final parse, it's quicker than using Selenium
    soup = BeautifulSoup(html, 'html.parser')

    # Gets whether it's group work or not, all group work specifications is stored under a tag called description details,
    # and it conveniently enough can be parsed out. There's a bunch of unrelated description details tags, so
    # we get all the ones that contain the exact text "Group", since that's a standard way of formatting
    # group projects or tasks worth a percentage of the mark for the course. The below is approximately the
    # format from the webpage:
    # <dt>Assessment Format: <dt> <dd>Group<dd>
    potential_group_tags = soup.find_all('dd')
    groupwork = False
    for potential_group_tag in potential_group_tags:
        if potential_group_tag.get_text() == "Group":
            groupwork = True
            break
    if groupwork:
        print(f"Groupwork found in {course}!")
    else:
        print(f"Groupwork not found in {course}!")
    driver.get("https://www.unsw.edu.au/course-outlines")

driver.quit()